version: "3.8"
services:
  app:
    build:
      args:
        user: juan
        uid: 1000  #echo $UID
      context: ./
      dockerfile: Dockerfile
    image: universidad-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - universidad

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - universidad

  db:
    image: mysql:8
    ports:
      - "33306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - universidad

networks:
  universidad:
    driver: bridge
volumes:
  mysql-data:
